### ISSUE TITLE
Replace Grunt with Rake?

### ISSUE THREAD

**Issue by huyderman** [aptoma/silex-bootstrap#2]
The projects/bootstrap uses several build/deploy tools; Composer, Guard, Capistrano, Bundler, NPM and Grunt; That's one PHP tool, three Ruby tools and two Node tools.

Should we consider consolidating this a bit? Rake can do pretty much the same as Grunt (we're not really doing anything fancy). In addition, Capistrano is based/inspired on Rake, so if you understand a `Capfile`, you'll probably understand a `Rakefile` and visa-versa. It also opens up for potential code reuse between Guard, Capistrano and Rake.

If we drop Grunt, we might also be able to drop npm. A lot of JS/Node libs (e.g. jshint, esprima) are available as gems or in composer.

**Comment by gunnarlium** [comment]
Grunt is the natural default for JS heavy projects, and is used by several Aptoma products already. It is easily (and already) integrated with Jenkins, and is easy to use. I believe it's better to use the technologies that the project uses, as long as there are adequate options available. Capistrano and Guard does not have proper PHP or JS counterparts, and are thus best handled by Ruby.

Unless I can see clear use case for something that would be easier and better with Rake rather than Grunt, I don't think we should change this.
